#!/bin/bash

defaultconfig=/usr/share/ubuntu-vm-builder/confs/default-conf
baseuserconf=/usr/share/ubuntu-vm-builder/confs/baseuser-conf
etcconfig=/etc/ubuntu-vm-builder
userconfig=$HOME/.ubuntu-vm-builder
configfile=""

# Search for a config param
for i
do
        if [ -n "$configfile" ]; then
		configfile=$i
		break
	fi
	case $i in
        -c)
                configfile=$i
        esac
done

configfile=${configfile:-}

#apply the default config
if [ -e "$defaultconfig" ]; then
	. $defaultconfig
else
	echo "Default not found at: $defaultconfig. Exiting"
	exit 1
fi

#apply the system config
if [ -e "$etcconfig" ]; then
        . $etcconfig
else
	echo "Creating config file $etcconfig"
	cp $baseuserconf $etcconfig
fi

if [ -n "$configfile" ]; then
	# A specific config has been specified
	if [ -e "$configfile" ]; then
		. $configfile
	else
		echo "Configuration file $configfile does not exist"
		exit 1
	fi
elif [ -e $userconfig ]; then
	# we have a user config file
	. $userconfig
else
	echo "Creating config file $userconfig"
	cp $baseuserconf $userconfig
	test -n "$CONFIG_OWNER" && chown "$CONFIG_OWNER:$CONFIG_OWNER" $userconfig
	chmod 600 $userconfig
fi
